*** Comments ***
Copyright (c) 2026 STMicroelectronics.
All rights reserved.

This software is licensed under terms that can be found in the LICENSE file
in the root directory of this software component.
If no LICENSE file comes with this software, it is provided AS-IS.


*** Settings ***
Documentation       This file contains the applicative constants used by <example_ll_lptim_pulse_counter>


*** Variables ***
${PULSE_NUMBER}=    1000    # Number of pulse to be count before generating    an interrupt
