/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'appli_dualslot.release_AC6+NUCLEO-C542RC' 
 * Target:  'release_AC6+NUCLEO-C542RC' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.2.0 */
#define USE_EXTERNAL_ENV


#endif /* PRE_INCLUDE_GLOBAL_H */
