*** Comments ***
[Documentation]    This file contains the applicative constants used by <example_name>


*** Variables ***
${CONTROLLER_ID}=       101
${RESPONDER_ID}=        102
${FILTERED_ID}=         300

${NOMINAL_SPEED}=       500kbds
${DATA_SPEED}=          2Mbds
${MESSAGE_PING}=        1032547698BADCFE
${MESSAGE_PONG}=        0011223344556677
${FILTERED_MESSAGE}=    0000000000000000

${MAX_ATTEMPTS}=        10
${EXAMPLE_TIMEOUT}=     200ms
