/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'adv_trace_send_receive.release_IAR+NUCLEO-C542RC' 
 * Target:  'release_IAR+NUCLEO-C542RC' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.0.0 */
#define USE_EXTERNAL_ENV
/* STMicroelectronics::Utility:STM32CubeMX2 Config:ADVANCED_TRACE@1.0.0 */
#define ADV_TRACE_USER_CONF


#endif /* PRE_INCLUDE_GLOBAL_H */
