/**
  ******************************************************************************
  * file           : example.c
  * brief          : example program body
  ******************************************************************************
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "example.h"

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* @user: Set the timeout period, in milliseconds, of the UART on reception of a character from the terminal input */
#define RX_TIMEOUT 10000U
#define TX_TIMEOUT 1000U /* Timeout period, in milliseconds, of the UART on transmission of a character */
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
hal_uart_handle_t *pUART; /* pointer referencing the UART handle from the generated code */
/* Private functions prototype -----------------------------------------------*/
/**
  * Function-like macros redefining low-level library functions (hooks) to enable direct use of high-level library
  * functions in the C library, precisely printf and getchar, under all the supported toolchains: GNU, IAR EWARM, AC6.
  * @user: Copy-paste the prototypes of the functions with their definitions in your application.
  */


/** ---------------------------------------------------------------------
  * Applicative code demonstrating the USB Device HID mouse
  * ---------------------------------------------------------------------
  */

/**
  * ########## Step 1 ##########
  * The init of the USB instance is triggered by the applicative code.
  * The initialization code is generated by STM32CubeMX2 under the targets folder.
  * So, you can find the related HAL|LL calls in stm32_usb_xx.c.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see mx_hal_def.h.
  */
app_status_t app_init(void)
{
  app_status_t return_status;
  pUART = mx_example_uart_init();

  if (mx_adv_trace_init() == SYSTEM_OK)
  {
    return_status = EXEC_STATUS_INIT_OK;
  }

  if (pUART != NULL)
  {
    return_status = EXEC_STATUS_INIT_OK;
    if (mx_example_hcd_init() != NULL)
    {
      if (app_usbx_init() == 0)
      {
        return_status = EXEC_STATUS_INIT_OK;
      }
      else
      {
        return_status = EXEC_STATUS_ERROR;
      }
    }
    else
    {
      return_status = EXEC_STATUS_ERROR;
    }
  }
  else
  {
    return_status = EXEC_STATUS_ERROR;
  }
  return return_status;
} /* end app_init */


app_status_t app_process(void)
{
  app_status_t return_status = EXEC_STATUS_ERROR;

  app_usbx_process();

  return return_status;
} /* end app_process */


app_status_t app_deinit(void)
{
  mx_example_uart_deinit();
  mx_example_hcd_deinit();
  return EXEC_STATUS_OK;
} /* end app_deinit */
