/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'usbx_host_hid_no_os.release_IAR+NUCLEO-C5A3ZG' 
 * Target:  'release_IAR+NUCLEO-C5A3ZG' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Utility:STM32CubeMX2 Config:ADVANCED_TRACE@1.0.0 */
#define ADV_TRACE_USER_CONF


#endif /* PRE_INCLUDE_GLOBAL_H */
