/**
  ******************************************************************************
  * file           : example.c
  * brief          : example program body
  ******************************************************************************
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "example.h"
#include "mx_usbx_app.h"

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
hal_uart_handle_t *pUART; /* pointer referencing the UART handle from the generated code */
/* Private functions prototype -----------------------------------------------*/

/** ########## Step 1 ##########
  * The init of the USB instance is triggered by the applicative code.
  * The initialization code is generated by STM32CubeMX2 under the targets folder.
  * So, you can find the related HAL|LL calls in stm32_usb_xx.c.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see mx_hal_def.h.
  */
app_status_t app_init(void)
{
  app_status_t return_status;
  pUART = mx_example_uart_init();

  if (pUART != NULL)
  {
    return_status = EXEC_STATUS_INIT_OK;
    if (app_usbx_init() != 0)
    {
      return_status = EXEC_STATUS_ERROR;
    }
  }
  else
  {
    return_status = EXEC_STATUS_ERROR;
  }
  return return_status;
} /* end app_init */


/** Deinitializes the USB instance before leaving the scenario.
  * The de-initialization code is generated by STM32CubeMX2 under the targets folder.
  * So, you can find the related HAL|LL calls in stm32_usb_xxx.c.
  * All the aliases used here are generated by STM32CubeMX2 under the targets folder: see mx_hal_def.h.
  */
app_status_t app_deinit(void)
{
  mx_example_pcd_deinit();
  return EXEC_STATUS_OK;
} /* end app_deinit */
