/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'filex_nor_multi_access_freertos.release_IAR+NUCLEO-C562RE' 
 * Target:  'release_IAR+NUCLEO-C562RE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.1.0 */
#define USE_EXTERNAL_ENV
/* STMicroelectronics::File System:STM32CubeMX2 Config:FileX@2.1.0 */
#define FX_INCLUDE_USER_DEFINE_FILE
/* STMicroelectronics::File System:STM32CubeMX2 Config:LevelX@2.1.0 */
#define LX_INCLUDE_USER_DEFINE_FILE


#endif /* PRE_INCLUDE_GLOBAL_H */
