# file-format: 1.0.0
if(CMAKE_BUILD_TYPE STREQUAL "release_GCC_NUCLEO-C562RE")
  set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES SUFFIX ".elf")
  target_compile_options(${CMAKE_PROJECT_NAME} PUBLIC ${CPU_FLAGS})
  target_compile_options(${CMAKE_PROJECT_NAME} PUBLIC "SHELL:-Os -fdata-sections -ffunction-sections -std=gnu11 -Wall -fstack-usage --specs=nano.specs --specs=nosys.specs -Werror=implicit-function-declaration ${CC_SECURE}")
  target_include_directories(${CMAKE_PROJECT_NAME} PUBLIC ../user_modifiable/_release_GCC_NUCLEO-C562RE ../../../../../../arch/cmsis/CMSIS/Core/Include ../generated/hal ../generated/middleware/freertos ../generated/middleware/usbx ../generated/parts/led ../../../../../../middleware/freertos/include ../../../../../../middleware/freertos/portable/GCC/ARM_CM33_NTZ/non_secure ../../../../../../middleware/usbx/common/core/inc ../../../../../../middleware/usbx/common/usbx_device_classes/inc ../../../../../../middleware/usbx/interfaces/usbx_stm32_device_controllers ../../../../../../middleware/usbx/interfaces/usbx_stm32_device_descriptors ../../../../../../middleware/usbx/ports/freertos/inc ../../../../../../part_drivers/led/gpio ../../../../../../stm32c5xx_dfp/Include ../../../../../../stm32c5xx_drivers/hal ../../../../../../stm32c5xx_drivers/ll ../../application)
  target_compile_definitions(${CMAKE_PROJECT_NAME} PUBLIC USBD_INCLUDE_USER_DESC_CONFIG_FILE STM32C562xx _RTE_)
  target_link_options(${CMAKE_PROJECT_NAME} PUBLIC -Wl,-Map=${CMAKE_PROJECT_NAME}.map -Wl,--gc-sections -Wl,--start-group -lc -lm -Wl,--end-group -static --specs=nano.specs --specs=nosys.specs ${CC_SECURE})
  target_link_options(${CMAKE_PROJECT_NAME} PUBLIC ${CPU_FLAGS})
elseif(CMAKE_BUILD_TYPE STREQUAL "debug_GCC_NUCLEO-C562RE")
  set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES SUFFIX ".elf")
  target_compile_options(${CMAKE_PROJECT_NAME} PUBLIC ${CPU_FLAGS})
  target_compile_options(${CMAKE_PROJECT_NAME} PUBLIC "SHELL:-g3 -O0 -fdata-sections -ffunction-sections -std=gnu11 -Wall -fstack-usage --specs=nano.specs --specs=nosys.specs -Werror=implicit-function-declaration ${CC_SECURE}")
  target_include_directories(${CMAKE_PROJECT_NAME} PUBLIC ../user_modifiable/_debug_GCC_NUCLEO-C562RE ../../../../../../arch/cmsis/CMSIS/Core/Include ../generated/hal ../generated/middleware/freertos ../generated/middleware/usbx ../generated/parts/led ../../../../../../middleware/freertos/include ../../../../../../middleware/freertos/portable/GCC/ARM_CM33_NTZ/non_secure ../../../../../../middleware/usbx/common/core/inc ../../../../../../middleware/usbx/common/usbx_device_classes/inc ../../../../../../middleware/usbx/interfaces/usbx_stm32_device_controllers ../../../../../../middleware/usbx/interfaces/usbx_stm32_device_descriptors ../../../../../../middleware/usbx/ports/freertos/inc ../../../../../../part_drivers/led/gpio ../../../../../../stm32c5xx_dfp/Include ../../../../../../stm32c5xx_drivers/hal ../../../../../../stm32c5xx_drivers/ll ../../application)
  target_compile_definitions(${CMAKE_PROJECT_NAME} PUBLIC USBD_INCLUDE_USER_DESC_CONFIG_FILE STM32C562xx _RTE_)
  target_link_options(${CMAKE_PROJECT_NAME} PUBLIC -Wl,-Map=${CMAKE_PROJECT_NAME}.map -Wl,--gc-sections -Wl,--start-group -lc -lm -Wl,--end-group -static --specs=nano.specs --specs=nosys.specs ${CC_SECURE})
  target_link_options(${CMAKE_PROJECT_NAME} PUBLIC ${CPU_FLAGS})
endif()

# Clean .map and .elf file
set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/${CMAKE_PROJECT_NAME}.map")
set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/${CMAKE_PROJECT_NAME}.elf")