/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'stcryptolib_integrity_hash_sha2.release_IAR+NUCLEO-C562RE' 
 * Target:  'release_IAR+NUCLEO-C562RE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.0.0 */
#define USE_EXTERNAL_ENV
/* STMicroelectronics::Security:STCryptoLib:CMOX API@4.0.4 */
/* Enabling global cmox configuration file */
#define CMOX_DEFAULT_FILE "mx_cmox_config.h"


#endif /* PRE_INCLUDE_GLOBAL_H */
