/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'oemirot.release_AC6+NUCLEO-C5A3ZG'
 * Target:  'release_AC6+NUCLEO-C5A3ZG'
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.2.0 */
#define USE_EXTERNAL_ENV
/* STMicroelectronics::Security:MCUboot:Core@1.0.0 */
#define MCUBOOT_DOUBLE_SIGN_VERIF
/* STMicroelectronics::Security:STM32CubeMX2 Config:STFCF@1.0.0 */
/* Enabling global STFCF configuration file */
#define MBEDTLS_CONFIG_FILE "mx_stfcf_config.h"


#endif /* PRE_INCLUDE_GLOBAL_H */
