/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'sequencer_gpio_toggle.release_IAR+NUCLEO-C542RC' 
 * Target:  'release_IAR+NUCLEO-C542RC' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.0.0 */
#define USE_EXTERNAL_ENV
/* STMicroelectronics::Utility:STM32CubeMX2 Config:SEQUENCER@1.0.0 */
#define SEQ_USER_CONFIG


#endif /* PRE_INCLUDE_GLOBAL_H */
