/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'oemirot.release_IAR+NUCLEO-C5A3ZG'
 * Target:  'release_IAR+NUCLEO-C5A3ZG'
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.0.0 */
#define USE_EXTERNAL_ENV
/* STMicroelectronics::Security:MCUboot:Core@1.0.0 */
#define MCUBOOT_DOUBLE_SIGN_VERIF
/* STMicroelectronics::Security:STCryptoLib:CMOX API@4.0.4 */
/* Enabling global cmox configuration file */
#define CMOX_DEFAULT_FILE "mx_cmox_config.h"
/* STMicroelectronics::Security:STM32CubeMX2 Config:STFCF@1.0.0 */
/* Enabling global STFCF configuration file */
#define MBEDTLS_CONFIG_FILE "mx_stfcf_config.h"


#define NDEBUG

#define OEMIROT_DEV_MODE

#define ROT_MBEDTLS_MEM_BUF_LEN 0x1000

#endif /* PRE_INCLUDE_GLOBAL_H */
