/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'hal_fdcan_two_boards_com_it_responder.release_IAR+NUCLEO-C562RE' 
 * Target:  'release_IAR+NUCLEO-C562RE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* STMicroelectronics::Device:STM32CubeMX2 Config:RCC@2.0.0 */
#define USE_EXTERNAL_ENV


#endif /* PRE_INCLUDE_GLOBAL_H */
